[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v"
testpaths = ["tests"]
pythonpath = ["src"]

[tool.flake8]
max-line-length = 106
exclude = [".git", "__pycache__", "build", "dist", ".venv"]
extend-ignore = ["E203", "W503"]

[tool.mypy]
strict = true
ignore_missing_imports = true
files = ["src"]

[tool.isort]
profile = "black"
